### ISSUE TITLE
オブジェクトの角度の件

### ISSUE THREAD

**Issue by enetto** [wakiyamap/monacoin-nodemap#7]
main.jsの224.225行目の

_// 最後の-95.8は微妙な数値にしないとバグって変な角度になるのでその調整……誰か直して
object.rotation.set(0.0 ,longitude * (Math.PI / 180), latitude * (Math.PI / 180) - 95.8);_

の部分を

object.rotation.set(0.0 , longitude * (Math.PI / 180.0) , (270.0 + latitude) * (Math.PI / 180.0));

に変更してみました。
変更した場所は、"(270.0 + latitude) * (Math.PI / 180.0)"の緯度に対するZ軸の回転部分のみですがデバッグして、きちんとバグらずに同じ結果になってるのは確認してます。
もし差し支えなければこちらのほうでどうでしょうか？

**Comment by wakiyamap** [comment]
確認しました。ありがとうございます！
一応ですが、プルリクエストにされる気はないという事でよろしいですか？

まだやったことが無いとかでしたら練習に協力させていただきますが・・・・・・

**Comment by enetto** [comment]
すみません・・・、やったことがないのでご指導お願いします。

**Comment by wakiyamap** [comment]
1.編集するファイル(今回だと `js/main.js` )まで飛んで赤丸に囲まれているペンのマーク(編集マーク)をクリックします。
![image](https://user-images.githubusercontent.com/7189933/86092901-1fb01080-bae9-11ea-8e90-6fc7493e8cd5.png)


2.変更内容を書き換えて一番下に行き、コミット（変更内容の要約）を入力して `Propose changes` をクリックします。
![image](https://user-images.githubusercontent.com/7189933/86094693-d44b3180-baeb-11ea-826d-0c770f25478c.png)


3.ページ変移先で `Create pull request` をクリックします。
![image](https://user-images.githubusercontent.com/7189933/86094923-1f654480-baec-11ea-9f45-c3c681348f82.png)


4.変更内容(今回だとこのissue #7 に関係していて issue #1 を直しました辺りでしょうか？とりあえず一例として書いておきます。このままでもOK)を入力して `Create pull request` をクリックします。
![image](https://user-images.githubusercontent.com/7189933/86095163-7ec35480-baec-11ea-9a8e-6ac0d056c34a.png)

とりあえずこれで完了です！

分からなかったらまた聞いてください

**Comment by enetto** [comment]
pull request出来ました！
ありがとうございました

**Comment by wakiyamap** [comment]
Fix #8
